language: node_js
node_js:
   - "node"
addons:
   chrome: stable
before_install:
   - cd lib;
   - yarn install;
   - cd ../db;
   - yarn install;
   - cd ../examples;
   - yarn install;
   - cd ..
script:
   - cd lib;
   - yarn test;
   - cd ../db;
   - yarn test;
   - cd ../examples;
   - yarn test;
   - cd ..
after_success:
  - cd lib;
  - yarn coverage;
  - cd ../test;
  - yarn coverage;
  - cd ..
