// Copyright (C) 2019 rameshvk. All rights reserved.
// Use of this source code is governed by a MIT-style license
// that can be found in the LICENSE file.

"use strict";

const fs = require("fs");

function main() {
  let names = fs
    .readdirSync(__dirname + "/../db")
    .filter(
      name => name != "value.js" && name != "stream.js" && name != "index.js"
    );
  names.unshift("value.js", "stream.js");

  let text = names
    .map(name => fs.readFileSync(__dirname + "/../db/" + name).toString())
    .map(text => {
      return text
        .replace(/^import.*$/gm, "")
        .replace(/export /g, "")
        .replace(/^\/\/.*$/gm, "")
        .replace(/^".*$/gm, "");
    })
    .join("");
  text +=
    "\nmodule.exports = {Store, Dict, Text, Null, Ref, Field, run, field, Conn, Transformer, Stream};";
  fs.writeFileSync(__dirname + "/../dist/dotdb.js", preamble + text);
}

const preamble = `// Copyright (C) 2019 rameshvk. All rights reserved.
// Use of this source code is governed by a MIT-style license
// that can be found in the LICENSE file.
// **** Code generated by dotjs/x/generate_dist.js ***

"use strict";
`;

main();
